services:
  - type: web
    name: baisan-elementary-school
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python -m gunicorn baisan_site.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
